//! Carbon Breadcrumb (slice-a).
//!
//! Anatomy (docs + `_breadcrumb.scss`):
//! 1. [`breadcrumb`] — horizontal row, not interactive. Overflow menu is
//!    skipped (needs Menu / Wave 3).
//! 2. [`breadcrumb_item`] — one hierarchy level; the actual page link
//!    (`Role::Button`, FR-058).
//! 3. Separator — text `"/"` generated by [`breadcrumb`] between items,
//!    never by the item. Carbon uses `::after { content: '/' }`; Petra has
//!    no generated content, so the separator is a first-class child.
//!
//! Sizes are type tokens, not a row height: sm 16 / md 18 line-height.
//! This constructor ships the md/default type (`typography.body`).

use super::stack;
use super::text::text;
use super::tokens::SPACING_03;
use crate::geom::{Align, Axis};
use crate::tree::{Interaction, Key, Role, Semantics, ViewNode};

const ITEM_INTENTS: &[Interaction] = &[Interaction::Focus, Interaction::Click];

/// A location/path trail. Horizontal stack, no role, no interactions.
///
/// Separators are injected here: one `"/"` text node between adjacent
/// items, none after the last (Carbon `--no-trailing-slash` is the
/// portable default for a retained-mode tree).
pub fn breadcrumb(key: impl Into<Key>, crumbs: Vec<ViewNode>) -> ViewNode {
    let mut children = Vec::with_capacity(crumbs.len().saturating_mul(2).saturating_sub(1));
    for (i, crumb) in crumbs.into_iter().enumerate() {
        if i > 0 {
            let mut sep = text(format!("sep-{i}"), "/");
            sep.semantics = Semantics {
                role: Some(Role::Separator),
                ..Semantics::default()
            };
            children.push(sep);
        }
        children.push(crumb);
    }
    let mut node = stack(key, Axis::Horizontal, Some(SPACING_03), children);
    node.props.align = Some(Align::Center);
    node
}

/// One breadcrumb link. `label` is required (FR-058); role and Focus/Click
/// are set inside this function.
pub fn breadcrumb_item(key: impl Into<Key>, label: impl Into<String>) -> ViewNode {
    let label = label.into();
    stack(
        key,
        Axis::Horizontal,
        None,
        vec![text("label", label.clone())],
    )
    .interactive(Role::Button, label, ITEM_INTENTS)
}

#[cfg(test)]
mod tests {
    use super::{SPACING_03, breadcrumb, breadcrumb_item};
    use crate::geom::Axis;
    use crate::tree::{Interaction, Role, ViewNode};

    fn named<'a>(node: &'a ViewNode, key: &str) -> &'a ViewNode {
        fn walk<'a>(node: &'a ViewNode, key: &str) -> Option<&'a ViewNode> {
            if node.key.as_str() == key {
                return Some(node);
            }
            node.children.iter().find_map(|child| walk(child, key))
        }
        walk(node, key).unwrap_or_else(|| panic!("no descendant keyed `{key}`"))
    }

    fn child_keys(node: &ViewNode) -> Vec<&str> {
        node.children.iter().map(|c| c.key.as_str()).collect()
    }

    #[test]
    fn breadcrumb_exists_and_is_not_interactive() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("home", "Home"),
                breadcrumb_item("here", "Here"),
            ],
        );
        assert_eq!(node.key.as_str(), "trail");
        assert!(node.interactions.is_empty());
        assert!(!node.is_interactive());
        assert!(node.semantics.role.is_none());
        assert_eq!(node.props.axis, Some(Axis::Horizontal));
        assert_eq!(
            node.props.spacing.as_ref().map(|n| n.as_str()),
            Some(SPACING_03)
        );
    }

    #[test]
    fn breadcrumb_item_is_a_labelled_button() {
        let node = breadcrumb_item("home", "Home");
        assert_eq!(node.semantics.role, Some(Role::Button));
        assert_eq!(node.semantics.label.as_deref(), Some("Home"));
        assert!(node.interactions.contains(&Interaction::Focus));
        assert!(node.interactions.contains(&Interaction::Click));
        assert!(node.is_interactive());
        assert_eq!(named(&node, "label").props.text.as_deref(), Some("Home"));
    }

    #[test]
    fn breadcrumb_inserts_slash_separators_between_items() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("a", "Alpha"),
                breadcrumb_item("b", "Bravo"),
                breadcrumb_item("c", "Charlie"),
            ],
        );
        assert_eq!(child_keys(&node), ["a", "sep-1", "b", "sep-2", "c"]);
        assert_eq!(named(&node, "sep-1").props.text.as_deref(), Some("/"));
        assert_eq!(named(&node, "sep-2").props.text.as_deref(), Some("/"));
        assert_eq!(named(&node, "sep-1").semantics.role, Some(Role::Separator));
        assert!(
            child_keys(&node)
                .iter()
                .filter(|k| k.starts_with("sep-"))
                .count()
                == 2,
            "no trailing separator after the last item"
        );
    }

    #[test]
    fn breadcrumb_with_one_item_has_no_separator() {
        let node = breadcrumb("trail", vec![breadcrumb_item("only", "Only")]);
        assert_eq!(child_keys(&node), ["only"]);
    }
}
