//! Carbon Breadcrumb (slice-a).
//!
//! Anatomy (docs + `_breadcrumb.scss`):
//! 1. [`breadcrumb`] — horizontal row, not interactive. Overflow menu is
//!    skipped (needs Menu / Wave 3).
//! 2. [`breadcrumb_item`] — one hierarchy level you can go back to. Carbon
//!    nests a `.cds--link` inside the item, so this **is** a
//!    [`super::link`]: same ink, same hover rule, same role.
//! 3. [`breadcrumb_item_current`] — the level you are standing on.
//!    Carbon marks it `[aria-current='page']` / `.cds--breadcrumb-item--current`,
//!    drops the link, and drops every interaction with it. Slice-a is
//!    explicit that a non-DOM renderer needs an own "current" boolean in
//!    place of the ARIA attribute; here that boolean is a second
//!    constructor, so a trail cannot forget to say where it is.
//! 4. Separator — text `"/"` generated by [`breadcrumb`] between items,
//!    never by the item. Carbon uses `::after { content: '/' }`; Petra has
//!    no generated content, so the separator is a first-class child.
//!
//! Sizes are type tokens, not a row height: sm 16 / md 18 line-height.
//! This constructor ships the md/default type (`typography.body`).
//!
//! # Why the item is a link and not a styled label
//!
//! Until 2026-09-05 a crumb bound no ink of its own, so all three crumbs
//! and both separators resolved to `text.primary` and the row read as one
//! sentence with slashes in it. The operator's report was *"i dont
//! understand this one"*, which is the correct reaction to five identical
//! glyph runs. Carbon paints the leading crumbs `$link-primary` and the
//! last one `$text-primary`, and in one look that says *two places I can
//! go back to, one place I am*.
//!
//! Building the crumb out of [`super::link::link`] rather than copying its
//! two token inserts is deliberate: link ink and the hover rule are one
//! fact, and two copies of one fact drift.
//!
//! **Three channels, not one.** The operator is red-green colour blind, so
//! the blue is never allowed to be the whole signal: a crumb also
//! underlines under the pointer (Carbon's own `:hover` rule, carried by
//! [`super::link::link`]) where the current page never does, and a crumb is
//! in focus order where the current page is not.
//!
//! # T070 divergence, still open
//!
//! Carbon's default keeps a separator **after** the last item and the
//! reference capture (`39`-geometry `03-breadcrumb.png`, read 2026-09-05)
//! shows it. [`breadcrumb`] drops it, matching `--no-trailing-slash`. That
//! is round 3's operator question Q4 and is deliberately not answered here.

use super::stack;
use super::text::text;
use super::tokens::SPACING_03;
use crate::geom::{Align, Axis};
use crate::tree::{Key, Role, Semantics, ViewNode};

/// A location/path trail. Horizontal stack, no role, no interactions.
///
/// Separators are injected here: one `"/"` text node between adjacent
/// items, none after the last (Carbon `--no-trailing-slash` is the
/// portable default for a retained-mode tree).
pub fn breadcrumb(key: impl Into<Key>, crumbs: Vec<ViewNode>) -> ViewNode {
    let mut children = Vec::with_capacity(crumbs.len().saturating_mul(2).saturating_sub(1));
    for (i, crumb) in crumbs.into_iter().enumerate() {
        if i > 0 {
            let mut sep = text(format!("sep-{i}"), "/");
            sep.semantics = Semantics {
                role: Some(Role::Separator),
                ..Semantics::default()
            };
            children.push(sep);
        }
        children.push(crumb);
    }
    let mut node = stack(key, Axis::Horizontal, Some(SPACING_03), children);
    node.props.align = Some(Align::Center);
    node
}

/// One breadcrumb link: a level above the current page, which you can go
/// back to. `label` is required (FR-058).
///
/// This is [`super::link::link`], not a lookalike. Carbon nests
/// `.cds--link` inside `.cds--breadcrumb-item`, and a link is its words —
/// one `Text` leaf carrying the role, the interactions, `link-primary` ink
/// and the `underline@hover` rule. Wrapping it in a stack would put the
/// interactions on the wrapper and the hover rule on the child, and the
/// child is never the hovered node, so the rule would never resolve; that
/// is [`super::link`]'s own measured reason for the same shape.
pub fn breadcrumb_item(key: impl Into<Key>, label: impl Into<String>) -> ViewNode {
    super::link::link(key, label)
}

/// The crumb for the page you are on: Carbon's `[aria-current='page']`.
///
/// Not a link, not focusable, not clickable, and in the page's own ink
/// rather than link ink — all four are Carbon's rules for this item, and
/// all four are the channels that say *you are here* to someone who does
/// not read the hue.
///
/// [`Semantics::selected`] carries the boolean, because Petra's semantics
/// have no `current` and `selected` is what "this is the one of the set
/// that is in force" means everywhere else in this library
/// (`selection_is_declared_state_not_only_a_fill_colour`).
pub fn breadcrumb_item_current(key: impl Into<Key>, label: impl Into<String>) -> ViewNode {
    let label = label.into();
    let mut node = text(key, label.clone());
    node.semantics = Semantics {
        label: Some(label),
        selected: true,
        ..Semantics::default()
    };
    node
}

#[cfg(test)]
mod tests {
    use super::{SPACING_03, breadcrumb, breadcrumb_item, breadcrumb_item_current};
    use crate::component::tokens::{LINK_PRIMARY, TEXT_PRIMARY};
    use crate::frame::{PetrifiedFrame, TransitionActivity, Viewport, petrify};
    use crate::geom::{Axis, Size};
    use crate::testing::{Harness, validated_with};
    use crate::token::{ColorValue, Theme, ThemeMode, TokenName, TokenValue, standard_vocabulary};
    use crate::tree::{Interaction, NodeKind, Props, Registry, Role, ViewNode};

    fn token<'a>(node: &'a ViewNode, slot: &str) -> Option<&'a str> {
        node.props.tokens.get(slot).map(|name| name.as_str())
    }

    fn named<'a>(node: &'a ViewNode, key: &str) -> &'a ViewNode {
        fn walk<'a>(node: &'a ViewNode, key: &str) -> Option<&'a ViewNode> {
            if node.key.as_str() == key {
                return Some(node);
            }
            node.children.iter().find_map(|child| walk(child, key))
        }
        walk(node, key).unwrap_or_else(|| panic!("no descendant keyed `{key}`"))
    }

    fn child_keys(node: &ViewNode) -> Vec<&str> {
        node.children.iter().map(|c| c.key.as_str()).collect()
    }

    #[test]
    fn breadcrumb_exists_and_is_not_interactive() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("home", "Home"),
                breadcrumb_item("here", "Here"),
            ],
        );
        assert_eq!(node.key.as_str(), "trail");
        assert!(node.interactions.is_empty());
        assert!(!node.is_interactive());
        assert!(node.semantics.role.is_none());
        assert_eq!(node.props.axis, Some(Axis::Horizontal));
        assert_eq!(
            node.props.spacing.as_ref().map(|n| n.as_str()),
            Some(SPACING_03)
        );
    }

    /// A crumb is a link: the role, the label, the intents, the ink and the
    /// hover rule Carbon's `.cds--link` inside `.cds--breadcrumb-item` has.
    ///
    /// The ink is asserted **not** to be `text.primary` as well as to be
    /// `link-primary`, for the reason `link.rs` gives about row 15: the
    /// defect was a control that resolved to the same tone as the prose
    /// beside it, and one name for two tones would pass the positive half
    /// on its own. Falsify by replacing the body of `breadcrumb_item` with
    /// `text(key, label)`: the ink assertions fail first.
    #[test]
    fn breadcrumb_item_is_a_link_in_link_ink() {
        let node = breadcrumb_item("home", "Home");
        assert_eq!(node.kind, NodeKind::Text, "a crumb is its words");
        assert_eq!(node.props.text.as_deref(), Some("Home"));
        assert_eq!(node.semantics.role, Some(Role::Button));
        assert_eq!(node.semantics.label.as_deref(), Some("Home"));
        assert!(node.interactions.contains(&Interaction::Focus));
        assert!(node.interactions.contains(&Interaction::Click));
        assert!(
            node.interactions.contains(&Interaction::Hover),
            "without Hover the crumb is never hovered and `underline@hover` \
             never resolves, so the second channel is gone"
        );
        assert!(node.is_interactive());
        assert_eq!(token(&node, "foreground"), Some(LINK_PRIMARY));
        assert_ne!(token(&node, "foreground"), Some(TEXT_PRIMARY));
        assert_eq!(token(&node, "underline@hover"), Some(LINK_PRIMARY));
    }

    /// The current page is the one crumb that is not a link: no role, no
    /// interactions, page ink, and `selected` declared so the state is a
    /// fact and not only a tone.
    ///
    /// Falsify by returning `breadcrumb_item(key, label)` from
    /// `breadcrumb_item_current`: the interactions and the ink both fail.
    #[test]
    fn the_current_crumb_is_not_a_link_and_declares_itself_selected() {
        let node = breadcrumb_item_current("here", "Rebuild");
        assert_eq!(node.kind, NodeKind::Text);
        assert_eq!(node.props.text.as_deref(), Some("Rebuild"));
        assert_eq!(node.semantics.label.as_deref(), Some("Rebuild"));
        assert!(
            node.semantics.selected,
            "Carbon's `[aria-current='page']` has to survive into the tree"
        );
        assert_eq!(node.semantics.role, None, "the current page is not a link");
        assert!(node.interactions.is_empty());
        assert!(!node.is_interactive());
        assert_eq!(token(&node, "foreground"), Some(TEXT_PRIMARY));
        assert_ne!(token(&node, "foreground"), Some(LINK_PRIMARY));
        assert_eq!(token(&node, "underline@hover"), None);
    }

    /// A trail says both things at once, and the separator belongs to
    /// neither crumb.
    #[test]
    fn a_trail_ending_in_a_current_page_has_links_before_it_and_none_after() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("home", "Workspace"),
                breadcrumb_item("docs", "Fibers"),
                breadcrumb_item_current("here", "Rebuild"),
            ],
        );
        assert_eq!(
            child_keys(&node),
            ["home", "sep-1", "docs", "sep-2", "here"]
        );
        let links: Vec<&str> = node
            .children
            .iter()
            .filter(|c| c.semantics.role == Some(Role::Button))
            .map(|c| c.key.as_str())
            .collect();
        assert_eq!(links, ["home", "docs"], "only the leading crumbs are links");
        assert!(named(&node, "here").semantics.selected);
    }

    #[test]
    fn breadcrumb_inserts_slash_separators_between_items() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("a", "Alpha"),
                breadcrumb_item("b", "Bravo"),
                breadcrumb_item("c", "Charlie"),
            ],
        );
        assert_eq!(child_keys(&node), ["a", "sep-1", "b", "sep-2", "c"]);
        assert_eq!(named(&node, "sep-1").props.text.as_deref(), Some("/"));
        assert_eq!(named(&node, "sep-2").props.text.as_deref(), Some("/"));
        assert_eq!(named(&node, "sep-1").semantics.role, Some(Role::Separator));
        assert!(
            child_keys(&node)
                .iter()
                .filter(|k| k.starts_with("sep-"))
                .count()
                == 2,
            "no trailing separator after the last item"
        );
    }

    #[test]
    fn breadcrumb_with_one_item_has_no_separator() {
        let node = breadcrumb("trail", vec![breadcrumb_item("only", "Only")]);
        assert_eq!(child_keys(&node), ["only"]);
    }

    const VIEWPORT: Size = Size { w: 900.0, h: 700.0 };

    fn accepting_registry() -> Registry {
        Registry::with_vocabulary(standard_vocabulary())
    }

    fn petrify_lone(node: ViewNode) -> PetrifiedFrame {
        let root = ViewNode::new(NodeKind::Stack, "root")
            .with_props(Props {
                axis: Some(Axis::Vertical),
                ..Props::default()
            })
            .child(node);
        let registry = accepting_registry();
        let mut harness = Harness::new();
        let viewport = Viewport::new(VIEWPORT, ThemeMode::Dark);
        harness.scale = viewport.scale;
        petrify(
            1,
            validated_with(&root, &registry),
            &mut harness.ctx(),
            viewport,
            TransitionActivity::default(),
        )
    }

    fn color(theme: &Theme, name: &str) -> ColorValue {
        match theme.value(&TokenName::new(name).unwrap()).unwrap() {
            TokenValue::Color(c) => *c,
            other => panic!("{name} is not a colour: {other:?}"),
        }
    }

    /// Check C/D: every crumb, its separators, and the trail itself place
    /// with a real rect, none of them outside their parent.
    #[test]
    fn frame_geometry_has_no_degenerate_or_overflowing_placements() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("home", "Home"),
                breadcrumb_item("docs", "Docs"),
                breadcrumb_item("here", "Here"),
            ],
        );
        let frame = petrify_lone(node);
        assert!(!frame.placements.is_empty(), "nothing placed");
        for p in &frame.placements {
            assert!(
                p.rect.w > 0.0 && p.rect.h > 0.0,
                "{} placed with a degenerate rect {:?}",
                p.id,
                p.rect
            );
            assert!(
                !p.paint.overflowed,
                "{} drew content larger than its own rect",
                p.id
            );
            if let Some(parent_idx) = p.parent {
                let parent = &frame.placements[parent_idx];
                let fits = p.rect.x >= parent.rect.x - 0.01
                    && p.rect.y >= parent.rect.y - 0.01
                    && p.rect.x + p.rect.w <= parent.rect.x + parent.rect.w + 0.01
                    && p.rect.y + p.rect.h <= parent.rect.y + parent.rect.h + 0.01;
                assert!(
                    fits,
                    "{} (rect {:?}) extends outside its parent {} (rect {:?})",
                    p.id, p.rect, parent.id, parent.rect
                );
            }
        }
    }

    /// Check F: every crumb declares `Focus` and must be reachable; a
    /// breadcrumb has no disabled crumb, so there is no negative case.
    #[test]
    fn every_crumb_is_reachable_in_focus_order() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("home", "Home"),
                breadcrumb_item("here", "Here"),
            ],
        );
        let frame = petrify_lone(node);
        let focus = crate::focus::FocusTree::from_placements(
            &frame.placements,
            &std::collections::BTreeMap::new(),
        );
        let crumb_ids: Vec<&str> = frame
            .placements
            .iter()
            .filter(|p| p.semantics.role == Some(Role::Button))
            .map(|p| p.id.as_str())
            .collect();
        assert_eq!(crumb_ids.len(), 2, "expected both crumbs placed");
        let order = focus.order();
        for id in crumb_ids {
            assert!(
                order.iter().any(|o| o == id),
                "{id} declares Focus but is not in focus order"
            );
        }
    }

    /// Check E: crumb labels and the `"/"` separator against the page
    /// ground they are read on (`surface.base`, matching how `text()`
    /// itself is styled to sit on the base layer), read through
    /// `Props.opacity`.
    #[test]
    fn crumb_and_separator_text_clears_aa_contrast_on_the_page_ground() {
        const MIN_TEXT_CONTRAST: f32 = 4.5;
        use crate::component::tokens::SURFACE_BASE;
        for theme in [crate::token::light(), crate::token::dark()] {
            let bg = color(&theme, SURFACE_BASE);
            let node = breadcrumb(
                "trail",
                vec![
                    breadcrumb_item("home", "Home"),
                    breadcrumb_item("here", "Here"),
                ],
            );
            fn walk_text(node: &ViewNode, bg: ColorValue, theme: &Theme, min: f32) {
                if node.props.text.is_some()
                    && let Some(fg_name) = node.props.tokens.get("foreground")
                {
                    let opacity = node.props.opacity.unwrap_or(1.0);
                    let fg = color(theme, fg_name.as_str()).faded(opacity).over(bg);
                    let ratio = fg.contrast_ratio(bg);
                    assert!(
                        ratio >= min,
                        "{:?} at {ratio:.2}:1 against {} fails AA {min}:1",
                        node.key,
                        fg_name.as_str()
                    );
                }
                for child in &node.children {
                    walk_text(child, bg, theme, min);
                }
            }
            walk_text(&node, bg, &theme, MIN_TEXT_CONTRAST);
        }
    }
}
