//! Carbon Breadcrumb (slice-a).
//!
//! Anatomy (docs + `_breadcrumb.scss`):
//! 1. [`breadcrumb`] — horizontal row, not interactive. Overflow menu is
//!    skipped (needs Menu / Wave 3).
//! 2. [`breadcrumb_item`] — one hierarchy level; the actual page link
//!    (`Role::Button`, FR-058).
//! 3. Separator — text `"/"` generated by [`breadcrumb`] between items,
//!    never by the item. Carbon uses `::after { content: '/' }`; Petra has
//!    no generated content, so the separator is a first-class child.
//!
//! Sizes are type tokens, not a row height: sm 16 / md 18 line-height.
//! This constructor ships the md/default type (`typography.body`).

use super::stack;
use super::text::text;
use super::tokens::SPACING_03;
use crate::geom::{Align, Axis};
use crate::tree::{Interaction, Key, Role, Semantics, ViewNode};

const ITEM_INTENTS: &[Interaction] = &[Interaction::Focus, Interaction::Click];

/// A location/path trail. Horizontal stack, no role, no interactions.
///
/// Separators are injected here: one `"/"` text node between adjacent
/// items, none after the last (Carbon `--no-trailing-slash` is the
/// portable default for a retained-mode tree).
pub fn breadcrumb(key: impl Into<Key>, crumbs: Vec<ViewNode>) -> ViewNode {
    let mut children = Vec::with_capacity(crumbs.len().saturating_mul(2).saturating_sub(1));
    for (i, crumb) in crumbs.into_iter().enumerate() {
        if i > 0 {
            let mut sep = text(format!("sep-{i}"), "/");
            sep.semantics = Semantics {
                role: Some(Role::Separator),
                ..Semantics::default()
            };
            children.push(sep);
        }
        children.push(crumb);
    }
    let mut node = stack(key, Axis::Horizontal, Some(SPACING_03), children);
    node.props.align = Some(Align::Center);
    node
}

/// One breadcrumb link. `label` is required (FR-058); role and Focus/Click
/// are set inside this function.
pub fn breadcrumb_item(key: impl Into<Key>, label: impl Into<String>) -> ViewNode {
    let label = label.into();
    stack(
        key,
        Axis::Horizontal,
        None,
        vec![text("label", label.clone())],
    )
    .interactive(Role::Button, label, ITEM_INTENTS)
}

#[cfg(test)]
mod tests {
    use super::{SPACING_03, breadcrumb, breadcrumb_item};
    use crate::frame::{PetrifiedFrame, TransitionActivity, Viewport, petrify};
    use crate::geom::{Axis, Size};
    use crate::testing::{Harness, validated_with};
    use crate::token::{ColorValue, Theme, ThemeMode, TokenName, TokenValue, standard_vocabulary};
    use crate::tree::{Interaction, NodeKind, Props, Registry, Role, ViewNode};

    fn named<'a>(node: &'a ViewNode, key: &str) -> &'a ViewNode {
        fn walk<'a>(node: &'a ViewNode, key: &str) -> Option<&'a ViewNode> {
            if node.key.as_str() == key {
                return Some(node);
            }
            node.children.iter().find_map(|child| walk(child, key))
        }
        walk(node, key).unwrap_or_else(|| panic!("no descendant keyed `{key}`"))
    }

    fn child_keys(node: &ViewNode) -> Vec<&str> {
        node.children.iter().map(|c| c.key.as_str()).collect()
    }

    #[test]
    fn breadcrumb_exists_and_is_not_interactive() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("home", "Home"),
                breadcrumb_item("here", "Here"),
            ],
        );
        assert_eq!(node.key.as_str(), "trail");
        assert!(node.interactions.is_empty());
        assert!(!node.is_interactive());
        assert!(node.semantics.role.is_none());
        assert_eq!(node.props.axis, Some(Axis::Horizontal));
        assert_eq!(
            node.props.spacing.as_ref().map(|n| n.as_str()),
            Some(SPACING_03)
        );
    }

    #[test]
    fn breadcrumb_item_is_a_labelled_button() {
        let node = breadcrumb_item("home", "Home");
        assert_eq!(node.semantics.role, Some(Role::Button));
        assert_eq!(node.semantics.label.as_deref(), Some("Home"));
        assert!(node.interactions.contains(&Interaction::Focus));
        assert!(node.interactions.contains(&Interaction::Click));
        assert!(node.is_interactive());
        assert_eq!(named(&node, "label").props.text.as_deref(), Some("Home"));
    }

    #[test]
    fn breadcrumb_inserts_slash_separators_between_items() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("a", "Alpha"),
                breadcrumb_item("b", "Bravo"),
                breadcrumb_item("c", "Charlie"),
            ],
        );
        assert_eq!(child_keys(&node), ["a", "sep-1", "b", "sep-2", "c"]);
        assert_eq!(named(&node, "sep-1").props.text.as_deref(), Some("/"));
        assert_eq!(named(&node, "sep-2").props.text.as_deref(), Some("/"));
        assert_eq!(named(&node, "sep-1").semantics.role, Some(Role::Separator));
        assert!(
            child_keys(&node)
                .iter()
                .filter(|k| k.starts_with("sep-"))
                .count()
                == 2,
            "no trailing separator after the last item"
        );
    }

    #[test]
    fn breadcrumb_with_one_item_has_no_separator() {
        let node = breadcrumb("trail", vec![breadcrumb_item("only", "Only")]);
        assert_eq!(child_keys(&node), ["only"]);
    }

    const VIEWPORT: Size = Size { w: 900.0, h: 700.0 };

    fn accepting_registry() -> Registry {
        Registry::with_vocabulary(standard_vocabulary())
    }

    fn petrify_lone(node: ViewNode) -> PetrifiedFrame {
        let root = ViewNode::new(NodeKind::Stack, "root")
            .with_props(Props {
                axis: Some(Axis::Vertical),
                ..Props::default()
            })
            .child(node);
        let registry = accepting_registry();
        let mut harness = Harness::new();
        let viewport = Viewport::new(VIEWPORT, ThemeMode::Dark);
        harness.scale = viewport.scale;
        petrify(
            1,
            validated_with(&root, &registry),
            &mut harness.ctx(),
            viewport,
            TransitionActivity::default(),
        )
    }

    fn color(theme: &Theme, name: &str) -> ColorValue {
        match theme.value(&TokenName::new(name).unwrap()).unwrap() {
            TokenValue::Color(c) => *c,
            other => panic!("{name} is not a colour: {other:?}"),
        }
    }

    /// Check C/D: every crumb, its separators, and the trail itself place
    /// with a real rect, none of them outside their parent.
    #[test]
    fn frame_geometry_has_no_degenerate_or_overflowing_placements() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("home", "Home"),
                breadcrumb_item("docs", "Docs"),
                breadcrumb_item("here", "Here"),
            ],
        );
        let frame = petrify_lone(node);
        assert!(!frame.placements.is_empty(), "nothing placed");
        for p in &frame.placements {
            assert!(
                p.rect.w > 0.0 && p.rect.h > 0.0,
                "{} placed with a degenerate rect {:?}",
                p.id,
                p.rect
            );
            assert!(
                !p.paint.overflowed,
                "{} drew content larger than its own rect",
                p.id
            );
            if let Some(parent_idx) = p.parent {
                let parent = &frame.placements[parent_idx];
                let fits = p.rect.x >= parent.rect.x - 0.01
                    && p.rect.y >= parent.rect.y - 0.01
                    && p.rect.x + p.rect.w <= parent.rect.x + parent.rect.w + 0.01
                    && p.rect.y + p.rect.h <= parent.rect.y + parent.rect.h + 0.01;
                assert!(
                    fits,
                    "{} (rect {:?}) extends outside its parent {} (rect {:?})",
                    p.id, p.rect, parent.id, parent.rect
                );
            }
        }
    }

    /// Check F: every crumb declares `Focus` and must be reachable; a
    /// breadcrumb has no disabled crumb, so there is no negative case.
    #[test]
    fn every_crumb_is_reachable_in_focus_order() {
        let node = breadcrumb(
            "trail",
            vec![
                breadcrumb_item("home", "Home"),
                breadcrumb_item("here", "Here"),
            ],
        );
        let frame = petrify_lone(node);
        let focus = crate::focus::FocusTree::from_placements(
            &frame.placements,
            &std::collections::BTreeMap::new(),
        );
        let crumb_ids: Vec<&str> = frame
            .placements
            .iter()
            .filter(|p| p.semantics.role == Some(Role::Button))
            .map(|p| p.id.as_str())
            .collect();
        assert_eq!(crumb_ids.len(), 2, "expected both crumbs placed");
        let order = focus.order();
        for id in crumb_ids {
            assert!(
                order.iter().any(|o| o == id),
                "{id} declares Focus but is not in focus order"
            );
        }
    }

    /// Check E: crumb labels and the `"/"` separator against the page
    /// ground they are read on (`surface.base`, matching how `text()`
    /// itself is styled to sit on the base layer), read through
    /// `Props.opacity`.
    #[test]
    fn crumb_and_separator_text_clears_aa_contrast_on_the_page_ground() {
        const MIN_TEXT_CONTRAST: f32 = 4.5;
        use crate::component::tokens::SURFACE_BASE;
        for theme in [crate::token::light(), crate::token::dark()] {
            let bg = color(&theme, SURFACE_BASE);
            let node = breadcrumb(
                "trail",
                vec![
                    breadcrumb_item("home", "Home"),
                    breadcrumb_item("here", "Here"),
                ],
            );
            fn walk_text(node: &ViewNode, bg: ColorValue, theme: &Theme, min: f32) {
                if node.props.text.is_some()
                    && let Some(fg_name) = node.props.tokens.get("foreground")
                {
                    let opacity = node.props.opacity.unwrap_or(1.0);
                    let fg = color(theme, fg_name.as_str()).faded(opacity).over(bg);
                    let ratio = fg.contrast_ratio(bg);
                    assert!(
                        ratio >= min,
                        "{:?} at {ratio:.2}:1 against {} fails AA {min}:1",
                        node.key,
                        fg_name.as_str()
                    );
                }
                for child in &node.children {
                    walk_text(child, bg, theme, min);
                }
            }
            walk_text(&node, bg, &theme, MIN_TEXT_CONTRAST);
        }
    }
}
